# Generated by Django 5.2.9 on 2025-12-12 19:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_camera_region_alter_regionalmanager_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='period',
            field=models.CharField(default='daily', max_length=50),
        ),
        migrations.CreateModel(
            name='ComplianceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('helmet', models.BooleanField(default=False)),
                ('mask', models.BooleanField(default=False)),
                ('suit', models.BooleanField(default=False)),
                ('id_card', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_history', to='core.employee')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
