# Generated by Django 5.2.9 on 2026-03-10 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_facerecognitionresult_delete_facerecognitionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancehistory',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.camera'),
        ),
        migrations.AddField(
            model_name='facerecognitionresult',
            name='compliance_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.compliancehistory'),
        ),
    ]
