# Generated by Django 5.2.9 on 2026-03-12 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_compliancehistory_camera_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compliancehistory',
            name='camera',
        ),
        migrations.RemoveField(
            model_name='facerecognitionresult',
            name='compliance_record',
        ),
        migrations.CreateModel(
            name='SafetyViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recognized_name', models.CharField(default='Unknown', max_length=100)),
                ('helmet_status', models.CharField(max_length=50)),
                ('mask_status', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='violations/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_violations', to='core.employee')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
